import { Employee, Advance, PayrollPeriod, PayrollRecord } from '../types';

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    dni: '74839201',
    firstName: 'Rodrigo',
    lastName: 'Gómez Salazar',
    email: 'rodrigo.ventas@importrivero.com',
    phone: '+591 71234567',
    department: 'VENTAS',
    position: 'Ejecutivo de Ventas Mayoristas',
    hireDate: '2024-03-15',
    status: 'ACTIVE',
    paymentFrequency: 'MENSUAL',
    baseSalary: 4800,
    bankName: 'Banco Nacional',
    bankAccountNumber: '4010-8921-99',
  },
  {
    id: 'emp-2',
    dni: '63920184',
    firstName: 'Juan',
    lastName: 'Quispe Mamani',
    email: 'juan.logistica@importrivero.com',
    phone: '+591 78901234',
    department: 'LOGISTICA',
    position: 'Operador de Almacén & Despacho',
    hireDate: '2024-05-10',
    status: 'ACTIVE',
    paymentFrequency: 'SEMANAL',
    baseSalary: 750, // Bs/USD por semana
    bankName: 'Banco Mercantil',
    bankAccountNumber: '1029-4821-33',
  },
  {
    id: 'emp-3',
    dni: '58291047',
    firstName: 'Carlos',
    lastName: 'Vargas Torrico',
    email: 'carlos.chofer@importrivero.com',
    phone: '+591 76543210',
    department: 'LOGISTICA',
    position: 'Chofer Distribuidor de Carga',
    hireDate: '2023-11-01',
    status: 'ACTIVE',
    paymentFrequency: 'SEMANAL',
    baseSalary: 820, // por semana
    bankName: 'Banco Unión',
    bankAccountNumber: '5920-1192-88',
  },
  {
    id: 'emp-4',
    dni: '81920384',
    firstName: 'Patricia',
    lastName: 'Morales Silva',
    email: 'patricia.oficina@importrivero.com',
    phone: '+591 70011223',
    department: 'OFICINA',
    position: 'Encargada de Facturación & Compras',
    hireDate: '2023-08-15',
    status: 'ACTIVE',
    paymentFrequency: 'MENSUAL',
    baseSalary: 4200,
    bankName: 'Banco de Crédito (BCP)',
    bankAccountNumber: '2109-3847-55',
  },
  {
    id: 'emp-5',
    dni: '49201948',
    firstName: 'Pedro',
    lastName: 'Mendoza Aliaga',
    email: 'pedro.mendoza@importrivero.com',
    phone: '+591 73344556',
    department: 'LOGISTICA',
    position: 'Estibador & Control de Carga',
    hireDate: '2024-01-20',
    status: 'ACTIVE',
    paymentFrequency: 'SEMANAL',
    baseSalary: 680,
    bankName: 'Efectivo / Caja',
    bankAccountNumber: 'PAGO-EFECTIVO',
  },
  {
    id: 'emp-6',
    dni: '92810293',
    firstName: 'Sofía',
    lastName: 'Rios Camacho',
    email: 'sofia.ventas@importrivero.com',
    phone: '+591 72334411',
    department: 'VENTAS',
    position: 'Asesora de Ventas Tienda Central',
    hireDate: '2024-06-01',
    status: 'ACTIVE',
    paymentFrequency: 'MENSUAL',
    baseSalary: 3900,
    bankName: 'Banco Ganadero',
    bankAccountNumber: '3819-2049-11',
  },
];

export const INITIAL_ADVANCES: Advance[] = [
  {
    id: 'adv-1',
    employeeId: 'emp-2',
    employeeName: 'Juan Quispe Mamani',
    employeeDni: '63920184',
    amount: 150,
    reason: 'Urgencia médica familiar (medicamentos)',
    requestDate: '2026-08-26',
    status: 'PENDING',
    notes: 'Aprobado por Administración para descontar esta semana.',
  },
  {
    id: 'adv-2',
    employeeId: 'emp-1',
    employeeName: 'Rodrigo Gómez Salazar',
    employeeDni: '74839201',
    amount: 600,
    reason: 'Anticipo quincenal para pago de arriendo',
    requestDate: '2026-08-15',
    status: 'PENDING',
    notes: 'Descontar en la liquidación de fin de mes.',
  },
];

export const INITIAL_PERIODS: PayrollPeriod[] = [
  {
    id: 'per-sem-35',
    code: 'SEM-2026-W35',
    name: 'Semana 35 (25 Ago - 31 Ago 2026)',
    frequency: 'SEMANAL',
    startDate: '2026-08-25',
    endDate: '2026-08-31',
    year: 2026,
    periodNumber: 35,
    status: 'OPEN',
  },
  {
    id: 'per-mes-08',
    code: 'MES-2026-08',
    name: 'Mes de Agosto 2026 (01 Ago - 31 Ago)',
    frequency: 'MENSUAL',
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    year: 2026,
    periodNumber: 8,
    status: 'OPEN',
  },
  {
    id: 'per-sem-34',
    code: 'SEM-2026-W34',
    name: 'Semana 34 (18 Ago - 24 Ago 2026)',
    frequency: 'SEMANAL',
    startDate: '2026-08-18',
    endDate: '2026-08-24',
    year: 2026,
    periodNumber: 34,
    status: 'CLOSED',
    totalGross: 2250,
    totalNet: 2250,
    totalAdvances: 0,
  },
];

export const INITIAL_RECORDS: PayrollRecord[] = [
  {
    id: 'rec-1',
    periodId: 'per-sem-35',
    employeeId: 'emp-2',
    employee: INITIAL_EMPLOYEES[1],
    baseSalary: 750,
    workedDays: 7,
    overtimeHours: 4,
    overtimeAmount: 93.75, // 750/48 * 4 * 1.5
    bonusesAmount: 50,
    totalEarnings: 893.75,
    advancesDeduction: 150,
    otherDeductions: 0,
    totalDeductions: 150,
    netAmount: 743.75,
    status: 'DRAFT',
    items: [
      { id: 'i-1', type: 'EARNING', name: 'Sueldo Base Semanal (7 días)', amount: 750 },
      { id: 'i-2', type: 'EARNING', name: 'Horas Extras (4 hrs @ 150%)', amount: 93.75 },
      { id: 'i-3', type: 'EARNING', name: 'Bono Productividad Despacho', amount: 50 },
      { id: 'i-4', type: 'DEDUCTION', name: 'Descuento Adelanto (Urgencia médica)', amount: 150 },
    ],
  },
  {
    id: 'rec-2',
    periodId: 'per-sem-35',
    employeeId: 'emp-3',
    employee: INITIAL_EMPLOYEES[2],
    baseSalary: 820,
    workedDays: 7,
    overtimeHours: 2,
    overtimeAmount: 51.25,
    bonusesAmount: 0,
    totalEarnings: 871.25,
    advancesDeduction: 0,
    otherDeductions: 0,
    totalDeductions: 0,
    netAmount: 871.25,
    status: 'DRAFT',
    items: [
      { id: 'i-5', type: 'EARNING', name: 'Sueldo Base Semanal (7 días)', amount: 820 },
      { id: 'i-6', type: 'EARNING', name: 'Horas Extras (2 hrs @ 150%)', amount: 51.25 },
    ],
  },
  {
    id: 'rec-3',
    periodId: 'per-sem-35',
    employeeId: 'emp-5',
    employee: INITIAL_EMPLOYEES[4],
    baseSalary: 680,
    workedDays: 7,
    overtimeHours: 0,
    overtimeAmount: 0,
    bonusesAmount: 30,
    totalEarnings: 710,
    advancesDeduction: 0,
    otherDeductions: 0,
    totalDeductions: 0,
    netAmount: 710,
    status: 'DRAFT',
    items: [
      { id: 'i-7', type: 'EARNING', name: 'Sueldo Base Semanal (7 días)', amount: 680 },
      { id: 'i-8', type: 'EARNING', name: 'Bono Carga Pesada', amount: 30 },
    ],
  },
  {
    id: 'rec-4',
    periodId: 'per-mes-08',
    employeeId: 'emp-1',
    employee: INITIAL_EMPLOYEES[0],
    baseSalary: 4800,
    workedDays: 30,
    overtimeHours: 0,
    overtimeAmount: 0,
    bonusesAmount: 450, // Comisión de ventas
    totalEarnings: 5250,
    advancesDeduction: 600,
    otherDeductions: 120, // Seguro/Aportes
    totalDeductions: 720,
    netAmount: 4530,
    status: 'DRAFT',
    items: [
      { id: 'i-9', type: 'EARNING', name: 'Sueldo Base Mensual (30 días)', amount: 4800 },
      { id: 'i-10', type: 'EARNING', name: 'Comisión Ventas Mayoristas', amount: 450 },
      { id: 'i-11', type: 'DEDUCTION', name: 'Descuento Adelanto Quincenal', amount: 600 },
      { id: 'i-12', type: 'DEDUCTION', name: 'Aporte de Ley / Seguro', amount: 120 },
    ],
  },
  {
    id: 'rec-5',
    periodId: 'per-mes-08',
    employeeId: 'emp-4',
    employee: INITIAL_EMPLOYEES[3],
    baseSalary: 4200,
    workedDays: 30,
    overtimeHours: 5,
    overtimeAmount: 131.25,
    bonusesAmount: 150,
    totalEarnings: 4481.25,
    advancesDeduction: 0,
    otherDeductions: 105,
    totalDeductions: 105,
    netAmount: 4376.25,
    status: 'DRAFT',
    items: [
      { id: 'i-13', type: 'EARNING', name: 'Sueldo Base Mensual (30 días)', amount: 4200 },
      { id: 'i-14', type: 'EARNING', name: 'Horas Extras Cierre Facturación (5 hrs)', amount: 131.25 },
      { id: 'i-15', type: 'EARNING', name: 'Bono Cumplimiento', amount: 150 },
      { id: 'i-16', type: 'DEDUCTION', name: 'Aporte de Ley / Seguro', amount: 105 },
    ],
  },
  {
    id: 'rec-6',
    periodId: 'per-mes-08',
    employeeId: 'emp-6',
    employee: INITIAL_EMPLOYEES[5],
    baseSalary: 3900,
    workedDays: 30,
    overtimeHours: 0,
    overtimeAmount: 0,
    bonusesAmount: 280,
    totalEarnings: 4180,
    advancesDeduction: 0,
    otherDeductions: 97.5,
    totalDeductions: 97.5,
    netAmount: 4082.5,
    status: 'DRAFT',
    items: [
      { id: 'i-17', type: 'EARNING', name: 'Sueldo Base Mensual (30 días)', amount: 3900 },
      { id: 'i-18', type: 'EARNING', name: 'Comisión Ventas Tienda', amount: 280 },
      { id: 'i-19', type: 'DEDUCTION', name: 'Aporte de Ley / Seguro', amount: 97.5 },
    ],
  },
];
